version: '3.8'
services:
  web:
    build: .
    ports:
      - 8000:8010
    volumes:
      - .:/app
    environment:
      - DEBUG=1                    
      - DB_NAME=${DB_NAME}         
      - DB_USER=${DB_USER}        
      - DB_PASSWORD=${DB_PASSWORD} 
      - DB_PORT=5432               
    depends_on:
      - db
    env_file:
      - .env.docker
  
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
