# Generated by Django 5.2.4 on 2025-08-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categorias',
            field=models.ManyToManyField(related_name='categories', to='categories.category'),
        ),
    ]
