# Generated by Django 5.2.4 on 2025-08-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categorias',
            new_name='categories',
        ),
    ]
